FROM python:3.9.12

WORKDIR /app

COPY ./app.py /

RUN pip install Flask psycopg2 gunicorn flask_sqlalchemy marshmallow pyjwt

COPY ./scripts/init.sql ./docker-entrypoint-initdb.d

CMD ["gunicorn", "-b", "0.0.0.0:80", "app:app"]

EXPOSE 80