FROM python:3.9.12

WORKDIR /app

COPY ./app.py /

RUN pip install Flask psycopg2 gunicorn flask_sqlalchemy marshmallow marshmallow-sqlalchemy pyjwt flask-marshmallow flask_swagger_ui

CMD ["gunicorn", "-b", "0.0.0.0:8080", "app:app"]

EXPOSE 8080